// File generated by FlutterFire CLI — replace with your project values:
//   dart pub global activate flutterfire_cli
//   flutterfire configure
//
// Until then, demo mode (backend AUTH_DISABLED) works without Firebase.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        return web;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: '1:000000000000:web:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'britney-ai-placeholder',
    authDomain: 'britney-ai-placeholder.firebaseapp.com',
    storageBucket: 'britney-ai-placeholder.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: '1:000000000000:android:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'britney-ai-placeholder',
    storageBucket: 'britney-ai-placeholder.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: '1:000000000000:ios:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'britney-ai-placeholder',
    storageBucket: 'britney-ai-placeholder.appspot.com',
    iosBundleId: 'com.britneyai.britneyAi',
  );
}
